# ============================================================
# SONARQUBE PROJECT CONFIGURATION
# ============================================================

# Project Identification
sonar.projectKey=riwi-cine-nest
sonar.projectName=Cine-Backend-Nest
sonar.projectVersion=1.0.0

# Source Code & Tests
sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=src/**/*.spec.ts,test/**/*.spec.ts,test/**/*.e2e-spec.ts
sonar.exclusions=src/**/*.spec.ts,test/**,**/node_modules/**,dist/**,coverage/**,src/database/migrations/**,src/database/seeders/**

# Encoding & Coverage Reports
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
